### ISSUE TITLE
Object Capability bitmasks wrong

### ISSUE THREAD

**Issue by hcankaya** [Yubico/yubihsmrs#8]
Hi, 

Some capabilities seem to have wrong bitmasks.

file : object.rs
Line : 845 to 899

Wrong bitmasks :  
ObjectCapability::PutAsymmetricKey => (0, 0x05),
ObjectCapability::DeriveEcdh = (1, 0x05),   
ObjectCapability::GetPseudoRandom = (2, 0x05),      
ObjectCapability::PutTemplate =(3, 0x05),   
ObjectCapability::PutOtpAeadKey = (4, 0x05),

bitmask should be 0x08.

Best regards
Hakan

**Comment by aveenismail** [comment]
Hi Hakan,

You are correct. The bitmask is fixed now and will be included in the next version
